### ISSUE TITLE
Enumeration resource is not working on demo environment

### ISSUE THREAD

**Issue by fmendezh** [gbif/registry-spring-boot#23]
The API call to http://api.demo.gbif-dev.org/v1/enumeration/basic returns an empty list, the registry UI depends heavily on this resource to populate dropdown lists and other elements of controlled vocabularies

**Comment by mike-podolskiy90** [comment]
IT passed successfully. Also works locally.
In case of classpath reading error (it's PATH_MAPPING static variable which is populated by reflection) that should be logged 
`LOG.error("Unable to read the classpath for enumerations", e);`
but this string is not present in the log file

**Comment by fmendezh** [comment]
https://github.com/gbif/registry-spring-boot/issues/23 This issue is about to make it working in the running environment could be a packaging problem, I'd suggest to download the artifact and running it locally, you can also attach a remote debugger to find the issue

**Comment by mike-podolskiy90** [comment]
Fixed, tested on dev
